name: Build and Deploy Lab Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Lab Website Docker image
      run: |
        docker build --tag lab-website-renderer:latest --file ./.docker/Dockerfile .
    
    - name: Run cite process to update citations
      run: |
        docker run --rm --volume "$(pwd):/usr/src/app" lab-website-renderer:latest python3 _cite/cite.py
    
    - name: Build Jekyll site
      run: |
        docker run --rm --volume "$(pwd):/usr/src/app" lab-website-renderer:latest bundle exec jekyll build
    
    - name: Commit citation updates if any
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/citations.yaml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update citations via GitHub Actions"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
